### ISSUE TITLE
`addUpperIndex` in PassGen.js could account for spaces

### ISSUE THREAD

**Issue by atoponce** [z1shivam/GenPass#2]
With a default `length = 3`, the `password` variable is space-separated in the form of "word1 word2 word3". As such, the following code could pick an index location that is a space:

```javascript
addUpperIndex = secureRandom(password.length);
```

Thus, when applying:

```javascript
password =
  password.slice(0, addUpperIndex) +
  password.charAt(addUpperIndex).toUpperCase() +
  password.slice(addUpperIndex + 1);
}
```

The space would be capitalized instead of an alphabetic character.

Further, if `inclChar` or `inclNum` evaluate to `true`, then the index could point to a non-alphabetic character attempting to capitalize that instead.

As such, the passphrase "?quietly mouthy2 elsewhere" could be generated when toggles "Include Number", "Include UpperCase", and "Include Special Character" are enabled. This is because the indexes in the for loop could be pointing to "?", " ", and "2".

I'm guessing this is unintentional behavior. Because the default word length is 3, if "Include UpperCase" is toggled, there should be three capitalized characters. Similarly with 4 and 5 words, having four and five capitalized characters respectively.

Do you intend to have one capitalized character per word, or can there be multiple capitalized characters per word. IE, should it be something like "Word1 wOrd2 woRd3" or is "WoRD1 word2 word3" valid?

**Comment by z1shivam** [comment]
Hey Aaron, thanks a bunch for checking out the code! 🙌

When I started building this site, I was a bit of a JavaScript rookie. The whole thing was a spontaneous creation. I had this idea of making a password generator that generates sensible and robust passwords. Admittedly, it became a bit of a coding chaos – blame my lack of planning, especially those confusing variable names.

And since you again grabbed my attention towards the code, I can now see a lot of improvements. My idea was to make the password more memorable. So, in the default setting, you can get a password and remember it like 'apple mobile laptop with the capital L in laptop'. 

I know it is not working like this right now, it is randomly taking some letters and converting to uppercase. But I like your idea that if uppercase is selected then there should be one uppercase letter per word.

As I said, I was a beginner, and I made some mistakes. But don't worry, I will go through the code, and I will try to fix those issues. Wait till my next commit (maybe some hours).

**Comment by atoponce** [comment]
No worries! I also don't mind helping and submitting a pull request if you don't have the time. I just wanted to make sure I understood what your intent was when generating the passphrases, thus the issue. But I'm not in any rush, so don't feel rushed to push any code if you want to rework it. It's all good!

**Comment by z1shivam** [comment]
Oh, thank you. Since I had some free time and the code was quite messy, I decided to thoroughly review and refactor it, making it more readable. Additionally, I relocated the large array to the common.js file and separated the code for password and passphrase into two appropriately named files. The code is now functioning well, but I would greatly appreciate it if you could review all the JavaScript files to identify any further potential improvements.

**Comment by atoponce** [comment]
I'll look over the code later tonight and keep you posted.

**Comment by atoponce** [comment]
Looks great.

**Comment by z1shivam** [comment]
Thanks for your review. I also merged the PR for subresource integrity. I didn't know that we can verify the resources we are fetching. Thanks again for your help!! 🙌
